# This is a basic workflow that is manually triggered

name: arvix paper

on:
  schedule:
    # 预约工作：每天的 6:15（UTC+8）对应 22:15 UTC
    - cron: '15 22 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: 安装依赖
      run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - name: 运行脚本
      run: python main.py
